const TRIVIA_UPDATE_URL = 'trivia/TRIVIA_UPDATE_URL';
const TRIVIA_ADD_CHANNEL = 'trivia/TRIVIA_ADD_CHANNEL';
const TRIVIA_DEL_CHANNEL = 'trivia/TRIVIA_DEL_CHANNEL';
const TRIVIA_UPDATE_INTERVAL = 'trivia/TRIVIA_UPDATE_INTERVAL';
const TRIVIA_UPDATE_LENGTH = 'trivia/TRIVIA_UPDATE_LENGTH';
const TRIVIA_UPDATE_COUNT = 'trivia/TRIVIA_UPDATE_COUNT';
const TRIVIA_ACTIVE_INACTIVE = 'trivia/TRIVIA_ACTIVE_INACTIVE';
const TRIVIA_ADD_WINNER = 'trivia/TRIVIA_ADD_WINNER';
const TRIVIA_UPDATE_WINNER = 'trivia/TRIVIA_UPDATE_WINNER';
const TRIVIA_NEW_ROUND = 'trivia/TRIVIA_NEW_ROUND';

export {
  TRIVIA_UPDATE_URL,
  TRIVIA_ADD_CHANNEL,
  TRIVIA_DEL_CHANNEL,
  TRIVIA_UPDATE_INTERVAL,
  TRIVIA_UPDATE_LENGTH,
  TRIVIA_UPDATE_COUNT,
  TRIVIA_ACTIVE_INACTIVE,
  TRIVIA_ADD_WINNER,
  TRIVIA_UPDATE_WINNER,
  TRIVIA_NEW_ROUND,
};
