const POLL_ADD = 'poll/POLL_ADD';
const POLL_DEL = 'poll/POLL_DEL';
const POLL_OPTION_ADD = 'poll/POLL_OPTION_ADD';
const POLL_OPTION_DEL = 'poll/POLL_OPTION_DEL';
const POLL_VOTE_ADD = 'poll/POLL_VOTE_ADD';
const POLL_VOTE_DEL = 'poll/POLL_VOTE_DEL';
const POLL_ACTIVE_TRUE = 'poll/POLL_ACTIVE_TRUE';
const POLL_ACTIVE_FALSE = 'poll/POLL_ACTIVE_FALSE';

export {
  POLL_ADD,
  POLL_DEL,
  POLL_OPTION_ADD,
  POLL_OPTION_DEL,
  POLL_VOTE_ADD,
  POLL_VOTE_DEL,
  POLL_ACTIVE_TRUE,
  POLL_ACTIVE_FALSE,
};
