const ADD_CHANNEL_FACEBOOK = 'smedia/ADD_CHANNEL_FACEBOOK';
const ADD_CHANNEL_TWITTER = 'smedia/ADD_CHANNEL_TWITTER';
const ADD_CHANNEL_DISCORD = 'smedia/ADD_CHANNEL_DISCORD';
const ADD_CHANNEL_YOUTUBE = 'smedia/ADD_CHANNEL_YOUTUBE';

const DEL_CHANNEL_FACEBOOK = 'smedia/DEL_CHANNEL_FACEBOOK';
const DEL_CHANNEL_TWITTER = 'smedia/DEL_CHANNEL_TWITTER';
const DEL_CHANNEL_DISCORD = 'smedia/DEL_CHANNEL_DISCORD';
const DEL_CHANNEL_YOUTUBE = 'smedia/DEL_CHANNEL_YOUTUBE';

export {
  ADD_CHANNEL_FACEBOOK,
  ADD_CHANNEL_TWITTER,
  ADD_CHANNEL_DISCORD,
  ADD_CHANNEL_YOUTUBE,
  DEL_CHANNEL_FACEBOOK,
  DEL_CHANNEL_TWITTER,
  DEL_CHANNEL_DISCORD,
  DEL_CHANNEL_YOUTUBE,
};
