const BOT_JOIN_CHANNEL = 'bot/BOT_JOIN_CHANNEL';
const BOT_PART_CHANNEL = 'bot/BOT_PART_CHANNEL';
const BOT_CHANGE_OWNER = 'bot/BOT_CHANGE_OWNER';

export {
  BOT_JOIN_CHANNEL,
  BOT_PART_CHANNEL,
  BOT_CHANGE_OWNER,
};
